### ISSUE TITLE
Parameters of Stage III

### ISSUE THREAD

**Issue by Jason3900** [grammarly/gector#11] opened 2020-07-03 12:45 UTC
Hi! 
I've achieved re-implementing your paper's BERT result in training stage II. But after I finished the training Stage III, it seems that the improvement is not so obvious (F0.5 from 57.02 to 59.06). I don't know if I got the correct hyper-parameters settings. So could you please provide me with your settings on BERT in stage III?
```
skip_correct, tn_prob, tp_prob, cold_steps_count, tune_bert, n_epoch
```

**Comment by komelianchuk** [comment] 2020-07-03 13:11
Hi!
We used:
> skip_correct==1, tn_prob==1, tp_prob==1, cold_steps_count==1, tune_bert==1, n_epoch==20

I think it's a good improvement and you can tune f05 further with inference tweaks.
Consider using `additional_confidence`==0.1 and `min_error_probability`== 0.4 for precision/recall trade-off.

**Comment by Jason3900** [comment] 2020-07-03 13:23
Thanks! But...if the skip_correct=True, doesn't it mean that all the correct sentences will be skipped, while in the paper you said that there're errorful and error-free sentences in stage III? I don't quite follow this, could you explain a little?

**Comment by komelianchuk** [comment] 2020-07-03 13:52
We used this parameter in the early stages and later we added `tn_prob` and `tp_prob`.
If it's true then you can choose the ratio of TN sentences that will be picked from the data by setting `tn_prob` (1 - all TN sentences will be taken, 0 - all TN sentences will be dropped)
So `skip_correct==0` is the same with `skip_correct=1 and tn_prob=1`

**Comment by Jason3900** [comment] 2020-07-03 14:04
Thanks! 
Now the things is ……I exactly follow your settings. But it's still much lower than the best result in your paper (F0.5: 63.0).
![image](https://user-images.githubusercontent.com/55134225/86476087-6b2c1e00-bd78-11ea-9a11-5516dbfe9c5b.png)
Below are the results in Stage II:
![image](https://user-images.githubusercontent.com/55134225/86476219-b34b4080-bd78-11ea-8ade-b99830007581.png)
The cmd I use in stage III:
```
python train.py
--train_set data/stageIII_data/locness_preprocessed.train --dev_set data/stageIII_data/locness_preprocessed.dev
--model_dir output/finetune_stageIII_batch64_accum2_1gpu_with_pretrain_batch32_accum1_8gpu_bert
--vocab_path data/output_vocabulary
--pretrain_folder output/finetune_batch64_accum2_1gpu_with_pretrain_batch32_accum1_8gpu_bert --pretrain best
--accumulation_size 2 --batch_size 64 --n_epoch 20 --transformer_model bert
--cold_steps_count 1 --special_tokens_fix 0 --tune_bert 1 --skip_correct 1 --tp_prob 1 --tn_prob 1
```
Is there still something wrong ……？

**Comment by komelianchuk** [comment] 2020-07-03 14:50
63.0 F05 was got by using `additional_confidence==0.1` and `min_error_probability== 0.4` (it should improve f05 a bit)
But your recall after stage 2 is pretty low. 
What were your training parameters for the step2?
It should be `--skip_correct 1 --tp_prob 1 --tn_prob 0`

**Comment by Jason3900** [comment] 2020-07-03 14:57
@komelianchuk 
The stage III result was got with the bias and min_error params.
The low recall,...right, I noticed that, too.
In stage II, I use the following parameters:
```
--accumulation_size 2 --batch_size 64 --n_epoch 3 --transformer_model bert --cold_steps_count 2 --special_tokens_fix 0 --tn_prob 0
```

**Comment by komelianchuk** [comment] 2020-07-03 15:06
I have one thought that might explain this problem.
We calculate vocabulary on stage 2 data first and then used this fixed vocabulary during all three stages by setting `vocab_path` parameter.
If this parameter is not set then you will recalculate vocabulary after each stage and have new classes for linear layer each time.

**Comment by Jason3900** [comment] 2020-07-03 15:19
@komelianchuk 
Oh……I used the vocab_path param all the way with your project's `./data/output_vocabulary` . So, It should be the same.
The only difference might be the data amount of lang8, which is bigger than yours. But since stage II's result is similar to yours, can this difference lead to nearly 4 points lower? 
In your paper's table 5, training stage III brought a significant improvement in both Precision and Recall, while I got worse precision, I don't get it... ><
By the way, in stage I and stage II, I use `cold_steps_count==2` to freeze the encoder for the first two epochs, is it the right way?

**Comment by komelianchuk** [comment] 2020-07-03 15:26
Yes, it seems like everything you did is correct.
It's hard for me to understand what's wrong with your results.
My suggestion is to take either RoBERTa or XLNet model (we reported results for them after each step in table5/10) and try to compare scores after each step.

**Comment by Jason3900** [comment] 2020-07-03 15:29
@komelianchuk 
Okey... Thank you very much!
I'll try it later to see what's going wrong here. It's really confusing...

**Comment by Jason3900** [comment] 2020-07-06 02:09
@komelianchuk 
By the way, how did you choose the 9M training data in stage I? And since the error ratio in the table is 100%, did you filter all the correct sentence pairs before training?

**Comment by gurunath-p** [comment] 2020-07-06 03:59
@Jason3900 @komelianchuk what learning rate did you use for pre-training in stage-1?

**Comment by komelianchuk** [comment] 2020-07-07 10:21
@Jason3900 I've rerun the training for the step1 with the following parameters. I will let you know about the results.

`python train.py --train_set=pie9m-train-tagged.txt --dev_set=pie9m-dev-tagged.txt --model_dir=MODEL_DIR --vocab_path=data/_output_vocabulary --skip_correct=1 --tn_prob=0 --special_tokens_fix=1 --transformer_model=roberta --updates_per_epoch=10000 --batch_size=128 --accumulation_size=2 `

Yes, we filter correct sentences during this stage. 
We got files from [here](https://drive.google.com/file/d/1bl5reJ-XhPEfEaPjvO45M7w0yN-0XGOA/view) and cat all files together (a1 + a2 + a3 + a4 + a5)
Then we took the first 9m of sentences (so it mostly based on a1 file) ran preprocess_data.py on them, and then **shuffled** the data before train/dev splitting.

I suggest trying to train a model on preprocessed shuffled `a1` version of data with the parameters which I mentioned above.

**Comment by komelianchuk** [comment] 2020-07-07 10:22
@gurunath-p we used lr==10**(-3) duing cold steps and lr==10**(-5) for the rest of the training.
These values are set as default in the code.

**Comment by Jason3900** [comment] 2020-07-09 15:54
@komelianchuk 
I've also rerun the stage I on xlnet with 8 GPUS( batch_size=32 * accumulation_size=1 * ngpus=8 => 256), following exactly your instructions (of course with tokens_fix=0), but got bad results on conll 2014 test data.
Below are what I got after stage I.
![image](https://user-images.githubusercontent.com/55134225/87061790-c9587580-c23e-11ea-9c46-37c90976d3eb.png)

**Comment by komelianchuk** [comment] 2020-07-09 16:47
My Roberta-base model is still training.
In terms of f05, your results are close to ours (we got 49.9 after this stage), but precision/recall distribution is different.
Is it correct that you use iteration_count=5, min_error_probability=0, additional_confidence=0 in `predict.py` ?

I will reach you back once retraining is over.

**Comment by Jason3900** [comment] 2020-07-09 17:14
@komelianchuk 
Yeah. 
And there's a param you didn't list, the cold_steps_count is 4 by fefault, you pretrain the model with this param == 2 or 4?

**Comment by komelianchuk** [comment] 2020-07-09 17:24
We used cold_steps_count == 2 for stages 1-2 as was mentioned in the paper.

**Comment by Jason3900** [comment] 2020-07-09 17:26
@komelianchuk 
okay……I forgot to add this when pretraining this time, I'll try it again.

**Comment by komelianchuk** [comment] 2020-07-09 17:46
Sorry, that we did not change the default parameter for cold_steps_count in the code.
I will rerun training for XLNet as well.

**Comment by Jason3900** [comment] 2020-07-10 11:42
This is the result on roberta model after stage I (with the latest version of your project). 
![image](https://user-images.githubusercontent.com/55134225/87150673-1b53d680-c2e5-11ea-8f17-47d88d0415ea.png)
It seems that I still got low recall.

**Comment by komelianchuk** [comment] 2020-07-10 12:50
Hi, @Jason3900 
My training is still going on, but I've already got the following with RoBERTa (after 16 epoch)

```
CORRECT EDITS  : 753
PROPOSED EDITS : 1273
GOLD EDITS     : 2434
P = 0.591516103692
R = 0.309367296631
F_0.5 = 0.500265745416
Precision   : 0.5915
Recall      : 0.3094
F_0.5       : 0.5003
```

I've uploaded the exact stage 1 data to the google drive and granted permission to you.

**Comment by Jason3900** [comment] 2020-07-10 13:12
@komelianchuk 
Hi! Thank you! I've received it.
There's just one detail I want to confirm, the total lines of the data file you shared with me is 1606304 (train+dev). Well, if I feed the first 9M data of PIE synthetic corpus to the data_preprocess.py, it will return the info as below and save a file of 9M lines. I used the preprocessed data to split train/dev set, which means the train set contains 8,820,000 lines and the dev set contains 180000 lines before, and then train the model. What did I miss here? 
```
The size of raw dataset is 9000000
Overall extracted 9000000. Original TP 8513531. Original TN 486469
```

**Comment by komelianchuk** [comment] 2020-07-10 13:32
Have you shuffled preprocessed data before doing the split? 

It should be 9,000,008 lines in files that I've shared.
It appeared that we used 99/1 split for stage 1 (which I forgot, but hope that it should not be that important) 

```
   90000 dev-tagged.txt
 8910008 train-tagged.txt
 9000008 total
```

**Comment by Jason3900** [comment] 2020-07-10 13:42
@komelianchuk 
Yeah, I shuffled before the split step.
No...There's actually only a dir of just 769MB containing two files.
![image](https://user-images.githubusercontent.com/55134225/87160210-34648380-c2f5-11ea-895b-590891b92b3a.png)
By the way, for the split step, if the dev set is also part of synthetic data, is it possible that the dev set owns a different distribution from authentic data which may cause a problem that we didn't pick the real best model state?

**Comment by komelianchuk** [comment] 2020-07-10 13:56
After unzipping it should be more lines:
![image](https://user-images.githubusercontent.com/12952217/87162182-40891a80-c2ce-11ea-9f2b-0d149abe1000.png)

**Comment by komelianchuk** [comment] 2020-07-10 13:58
There are 8,499,729 TP in both files (8,414,641 in train and 85,088 in dev)

**Comment by Jason3900** [comment] 2020-07-10 13:59
well....but I got this after unzipping...
![image](https://user-images.githubusercontent.com/55134225/87162509-9d012f80-c2f8-11ea-92c9-71c62b463e8b.png)

**Comment by Jason3900** [comment] 2020-07-10 14:16
@komelianchuk 
So...Could you please check again and share me with a new copy?
Thanks a lot ^_^

**Comment by komelianchuk** [comment] 2020-07-10 14:26
Sure.
I've updated google drive with unzipped files.
Please let me know when you download them.

**Comment by Jason3900** [comment] 2020-07-10 14:32
@komelianchuk 
Thank you. I've finished the download.

**Comment by komelianchuk** [comment] 2020-07-10 14:36
Is everything OK with number of lines?

**Comment by Jason3900** [comment] 2020-07-10 14:46
Yeah, now it's okay.

**Comment by Jason3900** [comment] 2020-07-11 07:47
I think I may know what the problem is...
I rent a Tesla V100 GPU and train a BERT-based model on that. After 14 epochs, it already exceeded the best BERT-based pretrained model I trained. More precisely, both F0.5 and Recall is higher, so, maybe there's something to do with the batch_size as I used batch_size == 32 and accum_size == 1 with 8 gpu but batch_size == 64 and accum_size ==4 with a single Tesla V100 GPU .

**Comment by komelianchuk** [comment] 2020-07-13 09:00
Great that you find this!
I hope that you will succeed with reproducing results! Please let us know about your progress.

**Comment by Jason3900** [comment] 2020-07-13 09:33
Sure! Thanks for your help!

**Comment by shikha10799** [comment] 2020-07-13 16:36
> I think I may know what the problem is...
> I rent a Tesla V100 GPU and train a BERT-based model on that. After 14 epochs, it already exceeded the best BERT-based pretrained model I trained. More precisely, both F0.5 and Recall is higher, so, maybe there's something to do with the batch_size as I used batch_size == 32 and accum_size == 1 with 8 gpu but batch_size == 64 and accum_size ==4 with a single Tesla V100 GPU .

@Jason3900  Can you please elaborate on this problem more clearly which you found was stopping you from reproducing exact results?
Thanks a lot in advance!!

**Comment by Jason3900** [comment] 2020-07-14 00:49
@shikha10799 
Hi!
The thing is I use multi-gpu for training. Since `batch_size(in paper, which refers to 256 during pretraining) == batch_size(in script) * accumulation_size * n_gpus`, I set `batch_size = 32, accumulation_size = 1` for pretrain on 8 GTX-1080ti GPU. But in fact, the small batch_size drag the recall down distinctly. I made a control experiment on batch_size and found out that on the same conditions, `batch_size == 64` 's performance is much higher than `batch_size == 32`. Therefore, if you decide to train on multi-GPUs, then maybe you need to keep the batch_size == 64 or even higher (if OOM, you can use accumulation_size to accumulate the gradients each x iterations to simulate a greater batch_size ). I think that the `batch_size (in paper)` is only related to `batch_size (in script) * accumulation_size`.

**Comment by shikha10799** [comment] 2020-07-15 09:41
> @komelianchuk
> Thank you. I've finished the download.



> @shikha10799
> Hi!
> The thing is I use multi-gpu for training. Since `batch_size(in paper, which refers to 256 during pretraining) == batch_size(in script) * accumulation_size * n_gpus`, I set `batch_size = 32, accumulation_size = 1` for pretrain on 8 GTX-1080ti GPU. But in fact, the small batch_size drag the recall down distinctly. I made a control experiment on batch_size and found out that on the same conditions, `batch_size == 64` 's performance is much higher than `batch_size == 32`. Therefore, if you decide to train on multi-GPUs, then maybe you need to keep the batch_size == 64 or even higher (if OOM, you can use accumulation_size to accumulate the gradients each x iterations to simulate a greater batch_size ). I think that the `batch_size (in paper)` is only related to `batch_size (in script) * accumulation_size`.


> @shikha10799
> Hi!
> The thing is I use multi-gpu for training. Since `batch_size(in paper, which refers to 256 during pretraining) == batch_size(in script) * accumulation_size * n_gpus`, I set `batch_size = 32, accumulation_size = 1` for pretrain on 8 GTX-1080ti GPU. But in fact, the small batch_size drag the recall down distinctly. I made a control experiment on batch_size and found out that on the same conditions, `batch_size == 64` 's performance is much higher than `batch_size == 32`. Therefore, if you decide to train on multi-GPUs, then maybe you need to keep the batch_size == 64 or even higher (if OOM, you can use accumulation_size to accumulate the gradients each x iterations to simulate a greater batch_size ). I think that the `batch_size (in paper)` is only related to `batch_size (in script) * accumulation_size`.

thanks for the reply.You mean we need to increase the batch size in order to achieve higher accuracy and reproduce the results.

**Comment by shikha10799** [comment] 2020-07-15 09:44
> @shikha10799
> Hi!
> The thing is I use multi-gpu for training. Since `batch_size(in paper, which refers to 256 during pretraining) == batch_size(in script) * accumulation_size * n_gpus`, I set `batch_size = 32, accumulation_size = 1` for pretrain on 8 GTX-1080ti GPU. But in fact, the small batch_size drag the recall down distinctly. I made a control experiment on batch_size and found out that on the same conditions, `batch_size == 64` 's performance is much higher than `batch_size == 32`. Therefore, if you decide to train on multi-GPUs, then maybe you need to keep the batch_size == 64 or even higher (if OOM, you can use accumulation_size to accumulate the gradients each x iterations to simulate a greater batch_size ). I think that the `batch_size (in paper)` is only related to `batch_size (in script) * accumulation_size`.

thanks for the reply.You mean we need to increase the batch size in order to achieve higher accuracy and to match the results in the paper.

**Comment by Jason3900** [comment] 2020-07-15 09:46
@shikha10799 
to achieve higher recall, actually.

**Comment by shikha10799** [comment] 2020-07-15 09:55
Thanks.Can I have one more favour? I am also trying to reproduce the results in the paper using colab but the PIE dataset is very big to be uploaded in the google drive. Can you please share the link of the unzipped version of the PIE dataset in Google drive so that i may directly access it in colab from the shared section.Thanks a lot in advance.

**Comment by Jason3900** [comment] 2020-07-15 09:59
> Thanks.Can I have one more favour? I am also trying to reproduce the results in the paper using colab but the PIE dataset is very big to be uploaded in the google drive. Can you please share the link of the unzipped version of the PIE dataset in Google drive so that i may directly access it in colab from the shared section.Thanks a lot in advance.
You're welcome. I'll share the link later.

**Comment by Jason3900** [comment] 2020-07-15 11:20
@shikha10799 
Since the first 9M sentences only appear in a1 and a2, the dir only contains these two parts.
Please let me know when you finished saving~
https://drive.google.com/drive/folders/1W_AJmnCrtKDy12OFQUR76wFh6Ba7mLcN

**Comment by shikha10799** [comment] 2020-07-15 12:59
hi.I have saved it.Thankyou very much for the support. :-)

**Comment by Jason3900** [comment] 2020-07-17 04:49
@komelianchuk 
Hi! I still cannot get the same result after pretraining. Is it possible to provide me with the pretraining result with 4 GPUs which you mentioned earlier?

**Comment by komelianchuk** [comment] 2020-07-17 08:51
@Jason3900 
What result have you got on a single GPU?

We did not train all models with 4 GPUs. It was just an experimental setup which gives us approximately the same result, but we conducted all experiments mentioned in the paper mostly with a single GPU.

**Comment by Jason3900** [comment] 2020-07-17 11:22
@komelianchuk 
I haven't conducted a full pretraining process on a single GPU. But, on 4 GPUs, I got lower F0.5 on RoBERTa with `batch_size==64, accumulation_size == 4, updates_per_epoch == 10,000`, and the data for pretraining is given by you. Now I'm confused...Is it possible that the results on multi-GPUs is lower than on a single GPU?
```
CORRECT EDITS  : 658
PROPOSED EDITS : 1074
GOLD EDITS     : 2410
P = 0.612662942272
R = 0.273029045643
F_0.5 = 0.490605427975
Precision   : 0.6127
Recall      : 0.2730
F_0.5       : 0.4906
```

**Comment by komelianchuk** [comment] 2020-07-17 12:07
@Jason3900 I can not guarantee that with multiGPUs your results will be the same (especially because you are doing update based on 8x more data). 

This result I got with XLNet after retraining on stage1 data a couple of days ago on a single GPU (--skip_correct=1 --tn_prob=0 --special_tokens_fix=0 --transformer_model=xlnet --updates_per_epoch=10000 --batch_size=64 --accumulation_size=4 --cold_steps_count=2).
```
CORRECT EDITS  : 909
PROPOSED EDITS : 1619
GOLD EDITS     : 2552
P = 0.561457689932
R = 0.356191222571
F_0.5 = 0.50343376163
Precision   : 0.5615
Recall      : 0.3562
F_0.5       : 0.5034
```
They are even better than the results in the paper.
If you want to reproduce our results please use a single GPU.

**Comment by Jason3900** [comment] 2020-07-17 12:24
@komelianchuk 
Okay～thanks. I'll try.

**Comment by tonytan48** [comment] 2020-07-20 13:38
Hi,
Thank you for your discussion.
It seems that this thread has mainly discussed the performance comparison of stage 1 on CONLL 14 test set. I have some doubts on parameters used for stage II and III as well. I have used the same setting with 

python train.py --train_set=pie9m-train-tagged.txt --dev_set=pie9m-dev-tagged.txt --model_dir=MODEL_DIR --vocab_path=data/_output_vocabulary --skip_correct=1 --tn_prob=0 --special_tokens_fix=1 --transformer_model=roberta --updates_per_epoch=10000 --batch_size=128 --accumulation_size=2

And obtained 34.88 F0.5 on BEA19-dev, this is pretty much the same as in table 10 of GECToR paper.
But in paper's section 6 Trainining stages, it seems the fine-tuning stages 2 and 3 is only trained for 2-3 epochs. But this issue thread seems to state for BERT stage III the n_epochs is 20 as well. So I am wondering does stage II and III also need that much of training?

**Comment by tonytan48** [comment] 2020-07-20 13:46
And I suppose the train-dev split is also 98-2 for stage II and III?

**Comment by komelianchuk** [comment] 2020-07-21 09:22
@tonytan48 
1. We set n_epochs=20 and patience=3 for all stages, but for 2 and 3 stages model stop learning much earlier compared to stage 1. (after a couple of epochs)
2. Yes, we used 98/2 split for all stages.

**Comment by tonytan48** [comment] 2020-07-21 13:59
@komelianchuk 
Thank you for the prompt reply.
I am trying to reproduce the roberta results on stage 2 and stage 3. And evaluation was conducted on BEA-19 dev set.
I am able to get F0.5 at 34.88(paper table10 34.9) for stage 1. Using actually a1 dataset for pretraining only(8.86 million sentences)
For stage 2 I used the errorful sentences in BEA19 training set. On my implementation is 560,164 parallel sentences.
and obtained the following on BEA-19( Paper was 46.7)

![image](https://user-images.githubusercontent.com/10150598/88063515-b037b900-cb9c-11ea-9bdd-8135f7cf281d.png)

However for stage 3. Only wi+locness parallel sentences are used. I observed some performance drop. May I know is it possible to know your detailed corpora used for Stage III and the command that contains the parameters?

![image](https://user-images.githubusercontent.com/10150598/88064041-54216480-cb9d-11ea-9d85-225b676c82da.png)

**Comment by komelianchuk** [comment] 2020-07-21 14:44
@tonytan48 
Sure, here is a list of stage3 parameters for Roberta
```
  tune_bert: 1
  skip_correct: 1
  skip_complex: 0
  n_epoch: 20
  patience: 3
  max_len: 50
  min_len: 3
  batch_size: 64
  cold_steps_count: 0
  lr: 1e-5
  accumulation_size: 2
  lowercase_tokens: 0
  pieces_per_token: 5
  vocab_path: data/_output_vocabulary
  pretrain: MODEL_AFTER_STAGE2
  transformer_model: roberta
  updates_per_epoch: 0
  iteration_count: 5
  additional_confidence: 0
  tn_prob: 1
  tp_prob: 1
  special_tokens_fix: 1
```

**Comment by tonytan48** [comment] 2020-07-22 10:15
@komelianchuk 
Thank you for the prompt reply. That is helpful. I was able to get 49.57 on bea19-dev, still bit far from reported 50.9 though, guess I will run some more experiments on stage 2 and 3.
TP	FP	FN	Prec	Rec	F0.5
2896	2541	4565	0.5326	0.3882	0.4957


However, another bug I sometimes encounter is value error of 'nan loss'. After changing updates_per_epoch it resolves. May I know normally what is the cause and solution to 'nan loss' value error?

**Comment by komelianchuk** [comment] 2020-07-27 15:35
@tonytan48 
Hi!
Have you succeeded in getting better results that 49.57? If not, I guess you might try to use less lang8 sentences during stage2 (dump which we used is older and slightly smaller than the most recent one) 

`nan loss` usually means that you face a gradient exploding problem. I suggest using more data, bigger batches, shorter training in order to prevent it.

**Comment by tonytan48** [comment] 2020-07-28 07:35
@komelianchuk Thank you for the notices. May I know the scale of dataset of yours during stage 2 and 3? My collection of errorful sentences is 560,000 for stage 2 and it seems stage3 wi+locness only 34k is a little too small.
Question 2 is I am wondering what parameters did you used for XLNet stage 2 and 3?
I am also trying to reproduce XLNet results and obtained the following:
Stage 1:
![image](https://user-images.githubusercontent.com/10150598/88632955-ed450380-d0e6-11ea-81b0-b03a99008b12.png)
Stage 2:
![image](https://user-images.githubusercontent.com/10150598/88633053-11084980-d0e7-11ea-9554-2427f56d2a67.png)
And Stage 3:
![image](https://user-images.githubusercontent.com/10150598/88633152-31d09f00-d0e7-11ea-9fc9-3604400f1779.png)

For stage 3 the performance deteriorated. Also, for xlnet stage2 with patience of 3. My exit epoch is 10, which is significantly higher than 2-3. I suspect the update steps is too high for stage 2(downsampling on lang-8 may reduce this bias). Did you try using more data or more update_steps_per_epoch during stage 3? I observed both my experiment on roberta and xlnet has better result on stage2 and worse during stage3. Maybe this is due to the overfitting to errornous lang-8 dataset

**Comment by komelianchuk** [comment] 2020-07-28 11:05
@tonytan48 
The data sizes which we used are mentioned in table1 in the paper.

FYI.
I've uploaded the details about all training parameters that we used. I hope it might be useful:
https://github.com/grammarly/gector/blob/master/docs/training_parameters.md

**Comment by komelianchuk** [comment] 2020-07-28 11:07
I will close this issue because it becomes too big and unspecific. If you have further questions - please create new dedicated issues.

**Closed by komelianchuk** 2020-07-28 11:07 UTC
